### ISSUE TITLE
Illegal Resolver Invocation - Module Context hasn't been passed!

### ISSUE THREAD

**Issue by rwlnd** [Urigo/graphql-modules#350] opened 2019-03-03 00:23 UTC
When adding a DateTime type (https://github.com/waitandseeagency/graphql-type-datetime) as a scalar type to my schema, I get the following error when executing a graphql query that contains an actual DateTime field:

```
 "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "_resolverPath": "DateTime.serialize",
          "_moduleName": "C:\\path-to-graphql-api\\src\\modules\\app.ts_4478577798731519",
          "_detail": "Module Context hasn't been passed!",
          "stacktrace": [
            "Error: ",
            "      GraphQL-Modules Error: Illegal Resolver Invocation!",
            "        - Resolver #DateTime.serialize is invoked unsafely outside of GraphQL-Modules.",
            "        -- Detail: Module Context hasn't been passed!",
            "",
            "      Possible solutions:",
            "      - You may forget to pass context of the module to your GraphQL Server.",
            "      -- Check if it is passed like below;",
            "      ---  const { schema, context } = YourModule;",
            "      ---  new ApolloServer({ schema, context });'",
            "      - If you're using subscriptions with GraphQL-Modules, you have to pass 'subscriptions' without overriding it as well.",
            "      -- Check if it is passed like below;",
            "      ---  const { schema, context, subscriptions } = YourModule;",
            "      ---  new ApolloServer({ schema, context, subscriptions });'",
            "  ",
            "    at GraphQLModule.checkIfResolverCalledSafely (C:\\path-to-graphql-api\\node_modules\\@graphql-modules\\core\\src\\graphql-module.ts:677:13)",
            "    at GraphQLScalarType.typeResolvers.(anonymous function) [as serialize] (C:\\path-to-graphql-api\\node_modules\\@graphql-modules\\core\\src\\graphql-module.ts:706:22)",
            "    at completeLeafValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:641:37)",
            "    at completeValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:587:12)",
            "    at completeValueCatchingError (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:503:19)",
            "    at resolveField (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:447:10)",
            "    at executeFields (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:293:18)",
            "    at collectAndExecuteSubfields (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:717:10)",
            "    at completeObjectValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:707:10)",
            "    at completeValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:598:12)"
```

I did the same thing to add the JSON scalar (https://github.com/taion/graphql-type-json) and everything worked out perfectly there. Comparing both repo's didn't really help me further as both implementations seem quite similar. 

For completeness, I added the resolver:

```
export default {
    JSON: GraphQLJSON,
    DateTime: GraphQLDateTime,
}
```

and added the type to the schema:

`scalar DateTime`

Also, the info in the error message is not really that useful at first sight as the context IS passed to my module and when I only declare the JSON type, it works fine.

Any assistance would be very welcome here! Thanks.

**Comment by ardatan** [comment] 2019-03-05 00:17
Are passing the context to the server properly?
`const { schema, context } = YourModule;`
`new ApolloServer({ schema, context });`

**Comment by rwlnd** [comment] 2019-03-05 09:12
Hey @ardatan, I'm definitely passing the context to the server properly.
Digging a bit deeper in the code I found that the check that's causing the error, `checkIfResolverCalledSafely` , when a DateTime scalar is being resolved is wrapped in a huge IF block  which checks if we are NOT dealing with a scalar type: https://github.com/Urigo/graphql-modules/blob/master/packages/core/src/graphql-module.ts#L696. But we ARE dealing with a scalar type so I'm thinking that for some reason the code is not detecting `typeResolvers` to be an instanceof `GraphQLScalarType`. But then again it still puzzles me why it seems to work with the JSON scalar type... Going to dig a bit further but again, any assistance would be very welcome!

**Comment by ardatan** [comment] 2019-03-05 10:51
@rwlnd Oh, my bad. So, you have a scalar definition but it is not an instance of GraphQLScalarType. Then, it cannot understand if it is a regular resolver or scalar type. This is definitely a bug. For now could you do something like this;
```
export default {
    JSON: GraphQLJSON,
    DateTime: new GraphQLScalarType(GraphQLDateTime),
}
```

**Comment by rwlnd** [comment] 2019-03-05 13:07
@ardatan, thanks for the feedback. I tried your workaround but getting a different error this time: 

```
 "stacktrace": [
            "TypeError: Cannot read property 'serialize' of undefined",
            "    at GraphQLScalarType.serialize (C:\\path-to-graphql-api\\node_modules\\graphql-type-datetime\\node_modules\\graphql\\type\\definition.js:417:41)",
            "    at completeLeafValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:641:37)",
            "    at completeValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:587:12)",
            "    at completeValueCatchingError (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:503:19)",
            "    at resolveField (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:447:10)",
            "    at executeFields (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:293:18)",
            "    at collectAndExecuteSubfields (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:717:10)",
            "    at completeObjectValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:707:10)",
            "    at completeValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:598:12)",
            "    at completeValue (C:\\path-to-graphql-api\\node_modules\\graphql\\execution\\execute.js:565:21)"
          ]
```

On the initial error, one difference my colleague noticed that the `graphql-type-datetime` plugin has a dependency on graphql, unlike the `graphql-type-json`. So we're thinking that that's why the scalar type is not being detected as a `GraphQLScalarType` in `graphql-modules`.

**Comment by ardatan** [comment] 2019-04-03 07:31
I think the issue is solved on `graphql-type-datetime`. Closing the issue then. Open this issue again if the problem persists.

**Closed** 2019-04-03 07:30 UTC
Labels: bug, core
