### ISSUE TITLE
Unable to resolve providers - typeorm typedi integration 

### ISSUE THREAD

**Issue by itxuye** [Urigo/graphql-modules#243] opened 2018-12-28 12:09 UTC
How to use graphql-modules with typeorm and typedi  ,now I got some problems . 
```
GraphQL-Modules Error: Dependency Provider Not Found!
      - Provider #Repository couldn't be injected into Provider #Users
      -- Provider #Repository is not provided in #Module 591455874290757 scope!

      Possible solutions:
      - Make sure you have imported the module of Provider #Repository in the module of Provider 
```

**Comment by ardatan** [comment] 2018-12-28 18:56
GraphQL-Modules has built-in dependency injection system, so you might not need any other dependency injection system/logic. If you don’t provide Repository in any module inside application, this error is expected. So, could you share more details or reproduce a repo?

**Comment by Urigo** [comment] 2019-01-04 02:18
@itxuye can you share what did you end up doing?

**Comment by itxuye** [comment] 2019-01-04 03:58
@Urigo  Finally , i didn't use typeorm-typedi-extentions , [https://github.com/typeorm/typeorm-typedi-extensions](url) , because i can't register a 3rd IOC container in graphql-modules.

**Comment by ardatan** [comment] 2019-01-04 16:32
You can export DI container of a module using injector property, then pass it to TypeORM using useContainer function.

**Comment by itxuye** [comment] 2019-01-05 05:45
@ardatan Ok, thanks, i will try it .

**Comment by Urigo** [comment] 2019-01-05 10:21
if it's ok, I'll keep it open until we'll have an example somewhere that people can have a look at

**Comment by iamclaytonray** [comment] 2019-02-02 22:34
Since the [WhatsApp Clone](https://github.com/Urigo/WhatsApp-Clone-server) was released today, we could probably close this issue now.

**Closed** 2019-02-22 08:25 UTC

**Comment by Cassianokunsch** [comment] 2020-01-21 12:41
![image](https://user-images.githubusercontent.com/9349768/72805467-b4a50880-3c31-11ea-92f9-1d1551a92650.png)

![image](https://user-images.githubusercontent.com/9349768/72805509-cdadb980-3c31-11ea-8b6b-a0b483580591.png)

![image](https://user-images.githubusercontent.com/9349768/72805525-dd2d0280-3c31-11ea-82c8-7d73fcf197ce.png)

![image](https://user-images.githubusercontent.com/9349768/72805537-e7e79780-3c31-11ea-934a-770a62a41ccc.png)

![image](https://user-images.githubusercontent.com/9349768/72805553-f2099600-3c31-11ea-8ed0-1977aaeb82c9.png)

![image](https://user-images.githubusercontent.com/9349768/72805573-fd5cc180-3c31-11ea-9c73-f6d0944c89b3.png)

![image](https://user-images.githubusercontent.com/9349768/72805692-3bf27c00-3c32-11ea-8e1e-f7792c1f3a4a.png)


I have this problem and I can't solve it.

**Comment by walleXD** [comment] 2020-02-29 21:10
@Cassianokunsch  were you able to solve it?
